#!/usr/bin/env bash
# Pupa backend installer
# Usage: curl -fsSL https://raw.githubusercontent.com/pupa-app/pupa/main/install.sh | bash
#        bash install.sh --local   (when already inside the repo)
#
# What it does:
#   1. Checks for Python 3.11+ and uv (installs uv if missing)
#   2. Clones the repo to ~/pupa (or pulls latest if already there)
#      --local: skips clone/pull, uses the current directory as install dir
#   3. Installs backend deps via uv
#   4. Installs setup extras (qrcode, cryptography) for the onboarding wizard
#   5. Runs `make setup` to configure LLM provider, TLS, and optionally the service
#      (LLM credentials are NOT written to config — export them in your shell)
#   6. Installs the `pupa-backend` CLI to ~/.local/bin/
#
# After installation, run `make pair` in the install dir to mint a QR code for
# pairing your iPhone.

set -euo pipefail

REPO_URL="https://github.com/pupa-app/pupa-backend.git"
INSTALL_DIR="${PUPA_INSTALL_DIR:-$HOME/pupa}"

# ── Argument parsing ─────────────────────────────────────────────────────────

LOCAL=false
CLI_ONLY=false
for arg in "$@"; do
  case "$arg" in
    --local)    LOCAL=true ;;
    --cli-only) LOCAL=true; CLI_ONLY=true ;;
  esac
done

# ── Colours ─────────────────────────────────────────────────────────────────
if [ -t 1 ]; then
  BOLD='\033[1m'; GREEN='\033[0;32m'; YELLOW='\033[0;33m'; RED='\033[0;31m'; RESET='\033[0m'
else
  BOLD=''; GREEN=''; YELLOW=''; RED=''; RESET=''
fi

info()  { echo -e "${GREEN}▶${RESET} $*"; }
warn()  { echo -e "${YELLOW}⚠ $*${RESET}"; }
error() { echo -e "${RED}✗${RESET} $*" >&2; exit 1; }
step()  { echo -e "\n${BOLD}$*${RESET}"; }

if [ "$CLI_ONLY" = false ]; then
  # ── Dependency checks ──────────────────────────────────────────────────────

  step "Checking requirements…"

  # Python 3.11+
  if ! command -v python3 &>/dev/null; then
    error "Python 3.11+ is required. Install via: brew install python (macOS) or apt install python3 (Linux)"
  fi
  PY_VER=$(python3 -c 'import sys; print(f"{sys.version_info.major}{sys.version_info.minor:02d}")')
  if [ "$PY_VER" -lt 311 ]; then
    error "Python 3.11+ is required (found $(python3 --version))"
  fi
  info "Python $(python3 --version | cut -d' ' -f2) ✓"

  # git
  if ! command -v git &>/dev/null; then
    error "git is required. Install via: brew install git (macOS) or apt install git (Linux)"
  fi
  info "git $(git --version | cut -d' ' -f3) ✓"

  # uv — install if missing
  if ! command -v uv &>/dev/null; then
    warn "uv not found — installing…"
    curl -LsSf https://astral.sh/uv/install.sh | sh
    # Reload PATH so uv is available in this shell session.
    export PATH="$HOME/.cargo/bin:$HOME/.local/bin:$PATH"
  fi
  info "uv $(uv --version | cut -d' ' -f2) ✓"
fi

# ── Clone or update repo ─────────────────────────────────────────────────────

if [ "$LOCAL" = true ]; then
  # In-repo mode: use the current directory, skip all git operations.
  INSTALL_DIR="$(pwd)"
  step "Local mode — using existing repo at ${INSTALL_DIR}…"
  info "Skipping clone/pull (--local)"
else
  step "Setting up Pupa in ${INSTALL_DIR}…"
  if [ -d "$INSTALL_DIR/.git" ]; then
    info "Repository already exists — pulling latest…"
    git -C "$INSTALL_DIR" pull --ff-only
  else
    info "Cloning repository…"
    git clone "$REPO_URL" "$INSTALL_DIR"
  fi
fi

cd "$INSTALL_DIR"

# Show the version we just installed.
VERSION=$(git -C "$INSTALL_DIR" describe --tags --always 2>/dev/null || echo "dev")
info "Pupa $VERSION"

if [ "$CLI_ONLY" = false ]; then
  # ── Install dependencies ─────────────────────────────────────────────────────

  step "Installing backend dependencies…"
  make install-backend
  info "Backend deps installed ✓"

  step "Installing setup extras (qrcode + cryptography for TLS and QR pairing)…"
  cd backend && uv pip install -e '.[setup]' && cd ..
  info "Setup extras installed ✓"

  # ── Run the setup wizard ─────────────────────────────────────────────────────

  step "Running setup wizard…"
  echo ""
  echo "  The wizard will ask for your LLM provider, persistence settings,"
  echo "  TLS preferences, and whether to install a background service."
  echo "  LLM credentials are NOT stored in config — export them in your shell."
  echo ""
  make setup
fi

# ── Install CLI ───────────────────────────────────────────────────────────────

step "Installing pupa-backend CLI…"
BIN_DIR="$HOME/.local/bin"
mkdir -p "$BIN_DIR"
CLI_PATH="$BIN_DIR/pupa-backend"

# Thin wrapper delegating to the `pupa-backend` console script that
# `uv sync` installs into the repo venv. Split heredoc so INSTALL_DIR expands.
cat > "$CLI_PATH" << CLISCRIPT
#!/usr/bin/env bash
# pupa-backend — wrapper around the installed console script.
# Generated by install.sh; re-run install to update.
exec "${INSTALL_DIR}/backend/.venv/bin/pupa-backend" "\$@"
CLISCRIPT

chmod +x "$CLI_PATH"
info "pupa-backend installed to $CLI_PATH ✓"

if ! echo "$PATH" | tr ':' '\n' | grep -qx "$HOME/.local/bin"; then
  warn "~/.local/bin is not in your PATH."
  warn "Add this to ~/.zshrc or ~/.bashrc then restart your shell:"
  warn "  export PATH=\"\$HOME/.local/bin:\$PATH\""
fi

# ── Done ─────────────────────────────────────────────────────────────────────

echo ""
echo -e "${BOLD}Installation complete!${RESET}"
echo ""
echo "  Config:  ~/.pupa-backend/config.yml  (loaded at every startup; re-run 'pupa-backend setup' to change)"
echo ""
echo "  pupa-backend run            — start the backend"
echo "  pupa-backend stop           — stop it"
echo "  pupa-backend pair           — mint QR code for iPhone"
echo "  pupa-backend service-install— run as background service"
echo "  pupa-backend uninstall      — remove everything"
echo ""
echo "  LLM credentials must be in your shell env (not stored in config):"
echo "    Anthropic:  export ANTHROPIC_API_KEY=sk-ant-..."
echo "    Bedrock:    export AWS_PROFILE=your-profile"
echo ""
