"""Read/modify the `mcp_servers:` block in ~/.pupa-backend/config.yml.

Backs the `pupa-backend mcp` CLI (scripts/mcp.py). The mutation logic lives here
— importable and unit-testable — so the script stays a thin argparse + prompt
shell. Writes preserve the same header + `chmod 600` as the setup wizard so the
two never drift.

The block this manages is consumed at startup by
[`mcp_servers.py`](mcp_servers.py) (via `pupa_config` → `PUPA_MCP_SERVERS`).
Editing config.yml does NOT hot-reload a running backend — restart to apply.
"""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, Iterable, Mapping

from pupa_backend.pupa_config import YAML_FILE

_HEADER = (
    "# Pupa backend config — generated by `make setup`\n"
    "# Edit freely; re-run `make setup` to validate and regenerate.\n"
    "# openai_compatible and anthropic keys may be stored here (chmod 600).\n"
    "# AWS credentials are never stored — use ~/.aws/ or export env vars.\n\n"
)

# Server names become YAML keys and the `mcp_<name>` discovery spec, so keep
# them shell/JSON-safe: letters, digits, dash, underscore.
_NAME_RE = re.compile(r"^[A-Za-z0-9_-]+$")

_VALID_TRANSPORTS = frozenset({"stdio", "streamable_http", "sse", "websocket"})


def load_config(path: Path | None = None) -> dict:
    """Return the full parsed config.yml (or `{}` when it doesn't exist yet)."""
    import yaml  # type: ignore[import]

    p = path or YAML_FILE
    if not p.exists():
        return {}
    return yaml.safe_load(p.read_text()) or {}


def write_config(cfg: dict, path: Path | None = None) -> None:
    """Write the full config back, preserving the setup header + 0600 perms."""
    import yaml  # type: ignore[import]

    p = path or YAML_FILE
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(_HEADER + yaml.dump(cfg, default_flow_style=False, sort_keys=False))
    p.chmod(0o600)


def list_servers(cfg: dict) -> dict[str, dict]:
    """Return the `mcp_servers` block (empty dict when absent/malformed)."""
    block = cfg.get("mcp_servers")
    return dict(block) if isinstance(block, dict) else {}


def validate_name(name: str) -> None:
    if not name or not _NAME_RE.match(name):
        raise ValueError(
            f"invalid server name {name!r}: use letters, digits, '-' or '_' only."
        )


def _pairs_to_dict(pairs: Iterable[str]) -> dict[str, str]:
    """Parse `KEY=VALUE` strings (for --env / --header) into a dict."""
    out: dict[str, str] = {}
    for raw in pairs:
        if "=" not in raw:
            raise ValueError(f"expected KEY=VALUE, got {raw!r}.")
        k, v = raw.split("=", 1)
        k = k.strip()
        if not k:
            raise ValueError(f"empty key in {raw!r}.")
        out[k] = v
    return out


def build_entry(
    *,
    command: str | None = None,
    args: Iterable[str] | None = None,
    url: str | None = None,
    transport: str | None = None,
    env: Mapping[str, str] | None = None,
    headers: Mapping[str, str] | None = None,
    description: str | None = None,
) -> dict[str, Any]:
    """Assemble one MCP server connection entry (mirrors MultiServerMCPClient).

    Exactly one of `command` (stdio) or `url` (http/sse) must be given.
    `description` is an optional human one-liner surfaced in the agent's
    `get_tools` gate listing and in `/backend-tools` discovery (a meta key —
    stripped before the connection reaches MultiServerMCPClient).
    """
    if bool(command) == bool(url):
        raise ValueError("specify exactly one of command (stdio) or url (http/sse).")
    if transport is not None and transport not in _VALID_TRANSPORTS:
        raise ValueError(
            f"unknown transport {transport!r}; expected one of {sorted(_VALID_TRANSPORTS)}."
        )

    entry: dict[str, Any] = {}
    if command:
        entry["command"] = command
        arg_list = list(args or [])
        if arg_list:
            entry["args"] = arg_list
    else:
        entry["url"] = url
    if transport:
        entry["transport"] = transport
    if env:
        entry["env"] = dict(env)
    if headers:
        entry["headers"] = dict(headers)
    if description and description.strip():
        entry["description"] = description.strip()
    return entry


def atlassian_entry(
    *, url: str, username: str, token: str = "${CONFLUENCE_API_TOKEN}"
) -> dict[str, Any]:
    """Preset for the community `mcp-atlassian` (Confluence) stdio server.

    `token` defaults to a `${CONFLUENCE_API_TOKEN}` placeholder so the secret
    stays in the process env (interpolated at startup) rather than in config.yml.
    """
    return build_entry(
        command="uvx",
        args=["mcp-atlassian"],
        env={
            "CONFLUENCE_URL": url,
            "CONFLUENCE_USERNAME": username,
            "CONFLUENCE_API_TOKEN": token,
            # mcp-atlassian bundles FastMCP 2.x. Silence its startup banner and
            # update-check boxes ("Pin fastmcp < 3" / "Update available") so they
            # don't clutter `pupa-backend run`. (`off` is the only valid disable
            # value for the update check — it's a stable|prerelease|off literal.)
            "FASTMCP_SHOW_CLI_BANNER": "false",
            "FASTMCP_CHECK_FOR_UPDATES": "off",
        },
        description="Atlassian Confluence — search spaces, read and write pages.",
    )


# Default launch for the community @playwright/mcp server (npx
# @playwright/mcp@latest). `make install-playwright` / the setup wizard still
# install the browser binaries.
_PLAYWRIGHT_COMMAND = "npx"
_PLAYWRIGHT_ARGS = ["@playwright/mcp@latest"]
_PLAYWRIGHT_DESCRIPTION = (
    "Browser automation — navigate, click, screenshot, and extract content "
    "from real web pages."
)


def playwright_entry() -> dict[str, Any]:
    """Preset for the community `@playwright/mcp` stdio server.

    Playwright is now an ordinary `mcp_servers:` entry (no bespoke env var). The
    browser binaries still come from `npx --yes playwright install chromium` —
    run `make install-playwright` or pick Playwright in `make setup`.
    """
    return build_entry(
        command=_PLAYWRIGHT_COMMAND,
        args=list(_PLAYWRIGHT_ARGS),
        description=_PLAYWRIGHT_DESCRIPTION,
    )


def add_server(cfg: dict, name: str, entry: dict, *, overwrite: bool = False) -> dict:
    """Return a copy of `cfg` with `entry` added under `mcp_servers[name]`."""
    validate_name(name)
    block = dict(cfg.get("mcp_servers") or {})
    if name in block and not overwrite:
        raise ValueError(f"server {name!r} already exists; pass overwrite=True to replace.")
    block[name] = entry
    new = dict(cfg)
    new["mcp_servers"] = block
    return new


def remove_server(cfg: dict, name: str) -> dict:
    """Return a copy of `cfg` with `mcp_servers[name]` removed."""
    block = dict(cfg.get("mcp_servers") or {})
    if name not in block:
        raise KeyError(name)
    del block[name]
    new = dict(cfg)
    if block:
        new["mcp_servers"] = block
    else:
        new.pop("mcp_servers", None)  # drop an empty block entirely
    return new
